=== ewen-lbh/ewen-lbh-portfoliodb/database.schema.json
{
	"$schema": "http://json-schema.org/schema",
	"$id": "portfoliodb-database",
	"type": "array",
	"items": {
		"type": "object",
		"required": [
			"id",
			"metadata",
			"paragraphs",
			"title",
			"media",
			"links",
			"footnotes"
		],
		"properties": {
			"id": {
				"type": "string"
			},
			"metadata": {
				"type": "object"
			},
			"paragraphs": {
				"type": "object",
				"additionalProperties": {
					"type": "array",
					"items": {
						"type": "object",
						"required": [
							"id",
							"content"
						],
						"properties": {
							"id": {
								"type": "string"
							},
							"content": {
								"type": "string"
							}
						}
					}
				}
			},
			"title": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			},
			"media": {
				"type": "object",
				"additionalProperties": {
					"type": "array",
					"items": {
						"type": "object",
						"required": [
							"id",
							"alt",
							"title",
							"source",
							"content_type",
							"size",
							"dimensions",
							"duration",
							"online"
						],
						"properties": {
							"id": {
								"type": "string"
							},
							"alt": {
								"type": "string"
							},
							"title": {
								"type": "string"
							},
							"source": {
								"type": "string"
							},
							"content_type": {
								"type": "string"
							},
							"size": {
								"type": "number"
							},
							"dimensions": {
								"type": "object",
								"required": [
									"width",
									"height",
									"aspect_ratio"
								],
								"properties": {
									"width": {
										"type": "number"
									},
									"height": {
										"type": "number"
									},
									"aspect_ratio": {
										"type": "number"
									}
								}
							},
							"duration": {
								"type": "number"
							},
							"online": {
								"type": "boolean"
							}
						}
					}
				}
			},
			"links": {
				"type": "object",
				"additionalProperties": {
					"type": "array",
					"items": {
						"type": "object",
						"required": [
							"id",
							"name",
							"title",
							"url"
						],
						"properties": {
							"id": {
								"type": "string"
							},
							"name": {
								"type": "string"
							},
							"title": {
								"type": "string"
							},
							"url": {
								"type": "string"
							}
						}
					}
				}
			},
			"footnotes": {
				"type": "object",
				"additionalProperties": {
					"type": "array",
					"items": {
						"type": "object",
						"required": [
							"name",
							"content"
						],
						"properties": {
							"name": {
								"type": "string"
							},
							"content": {
								"type": "string"
							}
						}
					}
				}
			}
		}
	}
}

=== ewen-lbh/ewen-lbh-portfoliodb/examples/1/out/database.json
[
    {
        "id": "spotifydash",
        "metadata": {
            "created": "2021-05-29",
            "made with": [
                "svelte"
            ],
            "wip": true,
            "thumbnails": {
                
            },
            "colors": {
                "primary": "",
                "secondary": "",
                "tertiary": ""
            }
        },
        "title": {
            "fr": "spotifydash",
            "en": "spotifydash"
        },
        "paragraphs": {
            "fr": [],
            "en": []
        },
        "media": {
            "fr": [],
            "en": []
        },
        "links": {
            "fr": [
                {
                    "id": "code-source",
                    "name": "Code source",
                    "title": "",
                    "url": "https://github.com/ewen-lbh/spotifydash"
                }
            ],
            "en": [
                {
                    "id": "source-code",
                    "name": "Source code",
                    "title": "",
                    "url": "https://github.com/ewen-lbh/spotifydash"
                }
            ]
        },
        "footnotes": {
            "fr": [],
            "en": []
        }
    }
]
